spring.application.name=power-bridge

spring.datasource.url=jdbc:postgresql://localhost:5432/power-bridge
spring.datasource.username=postgres
spring.datasource.password=coditas@

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.multiTenancy=SCHEMA

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false

logging.level.org.flywaydb=DEBUG