spring.application.name=power-bridge

spring.datasource.url=jdbc:postgresql://localhost:5432/power-bridge
spring.datasource.username=postgres
spring.datasource.password=coditas@

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.multiTenancy=SCHEMA

spring.jpa.show-sql=true

spring.flyway.enabled=false

logging.level.org.flywaydb=DEBUG

jwt.secret=abcdefghijklmnopqrstuvwxyz1234567890
jwt.expiration=21600000