package com.coditas.powerbridge.enums;

public enum Role {
    SUPER_ADMIN, CUSTOMER, SALES_TEAM_MEMBER, STATE_HEAD, DISTRICT_HEAD, CITY_HEAD, LOCAL_TECHNICIAN, BILLER, CRM, SERVICE_PROVIDER, OPERATIONS_HEAD, BPO, MANAGEMENT_TEAM_MEMBER
}
